namespace: monitoring
resources:
# this for prometheus
- prometheus/manifests/clusterrole.yaml
- prometheus/manifests/deployment.yaml
- prometheus/manifests/service.yaml
- prometheus/manifests/pvc.yaml


configMapGenerator:
- name: prometheus-server-conf
  files:
  - prometheus/config-files/prometheus.rules
  - prometheus/config-files/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
