kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    route:
      receiver: microsoft-teams
      group_by: ['alertname', 'severity']
      group_wait: 10s
      repeat_interval: 30m

    receivers:
    - name: microsoft-teams
      webhook_configs:
      - url: 'http://prometheus-msteams:2000/alertmanger'
        send_resolved: true
